---
title: "Getting Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 6
)
library(scdown)
library(knitr)
```

`scdown` stays intentionally short:

1. build one `scdown` object
2. run quick exploratory summaries
3. run sample-aware tests only when needed

## Build an object

```{r}
obj <- scdown(scdown_example())
obj
```

## Explore

```{r}
map_res <- plot_map(obj)
marker_res <- explore_markers(obj, top_n = 3)
gene_res <- plot_gene(obj, genes = c("CD3D", "NKG7", "LYZ"))
sig_res <- plot_signature(obj, signatures = c("cytotoxic", "b_cell"))

kable(head(map_res$tables$embedding_cells, 6))
kable(marker_res$tables$top_marker_per_celltype)
kable(gene_res$tables$gene_average_by_celltype)
kable(sig_res$tables$signature_score_by_celltype)
```

## Test

```{r}
comp_test <- test_composition(obj)
sig_test <- test_signature(obj, signatures = c("cytotoxic", "b_cell"))

kable(comp_test$tables$composition_test_table)
kable(sig_test$tables$signature_test_table)
```

## Custom resources

```{r}
obj_custom <- scdown(
  scdown_example(),
  signatures = list(my_state = c("CD3D", "IL7R")),
  marker_panels = list(my_t_panel = c("CD3D", "TRAC"))
)

kable(plot_signature(obj_custom, signatures = "my_state")$tables$signature_score_by_celltype)
```

## Report

```{r}
report_path <- build_scdown_report(obj)
report_path
```
